package lk.ijse.backend.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class OrderDTO {

    // Auto-generated by DB — null when saving new order
    private Integer orderId;

    @NotBlank(message = "Customer ID is required")
    private String customerId;

    @NotBlank(message = "Item ID is required")
    private String itemId;

    // Service always overwrites this with the real DB item name
    // But @NotBlank would cause 400 if frontend sends empty string — use nullable instead (400-Bad Request)
    private String itemName;

    @Min(value = 1, message = "Quantity must be at least 1")
    private int quantity;

    //@Min only works on int/long, NOT on double → use @DecimalMin for double
    @DecimalMin(value = "0.01", message = "Price must be greater than 0")
    private double price;

    // Calculated server-side — never validated from client
    private double totalPrice;

    // Set by @CreationTimestamp in entity — not sent from client
    private LocalDateTime orderDate;
}